# Generated by Django 2.2.14 on 2022-05-16 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cust_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate5',
            field=models.IntegerField(),
        ),
    ]
