# Generated by Django 2.2.14 on 2022-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cust_user', '0002_auto_20220516_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='i',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rate5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
