# Generated by Django 2.2.14 on 2022-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=122)),
                ('con_email', models.CharField(max_length=122)),
                ('con_phone', models.CharField(max_length=12)),
                ('con_msg', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
