# Generated by Django 2.2.14 on 2022-05-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='con_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='con_msg',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='con_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='con_phone',
            new_name='phone',
        ),
    ]
